namespace: devops

image:
  repository: 192.168.1.63/devops_test/devops_test
  tag: v1.0
  pullPolicy: IfNotPresent

env:
  environment: staging
  db:
    user: stage_user
    password: stage_password
    host: stage-db.host.local
    port: 5432
    name: stage_db

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: devops_test.autoever.test
      paths:
        - path: /
          pathType: Prefix
  tls: []
