namespace: devops

image:
  repository: 192.168.1.63/devops_test/devops_test
  tag: v1.0
  pullPolicy: IfNotPresent

env:
  environment: production
  db:
    user: prod_user
    password: prod_password
    host: prod-db.host.local
    port: 5432
    name: prod_db

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: devops_test.autoever.prd
      paths:
        - path: /
          pathType: Prefix
  tls: []
