apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops_test.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops_test.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops_test.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_USER
              value: "{{ .Values.env.dbUser }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.dbPassword }}"
