apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-test-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "devops-test-helm.name" . }}
      env: {{ .Values.env.environment }}
  template:
    metadata:
      labels:
        app: {{ include "devops-test-helm.name" . }}
        env: {{ .Values.env.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENVIRONMENT
              value: "{{ .Values.env.environment }}"
            - name: DB_USER
              value: "{{ .Values.env.db.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.db.password }}"
            - name: DB_HOST
              value: "{{ .Values.env.db.host }}"
            - name: DB_PORT
              value: "{{ .Values.env.db.port }}"
          ports:
            - containerPort: 3000
