apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-test-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "devops-test-helm.name" . }}
  ports:
    - port: 3000
      targetPort: 3000
